### ISSUE TITLE
Human in the loop support?

### ISSUE THREAD

**Issue by TheMrguiller** [BrainBlend-AI/atomic-agents#33]
HI @KennyVaneetvelde,

I would like to know if there is any support for human in the loop in your agentic framework. I find that is interesting to have the option to check for the user any information or solution that the agentic framework is generating.

**Comment by KennyVaneetvelde** [comment]
Ahh, I can see you have in the past played with some of those frameworks that love going completely off the rails 😁 

Well, due to the nature of how you are encouraged to build with atomic agents, having a human in the loop is pretty easy..

Each agent you create is made to perform just a single "step". that begins and ends with that you want.

Mind you, a single step could include a multi-step reasoning if your output schema includes, say, a `List[str]` where each string is a thought.

```python
class ChatAgentOutputSchema(BaseIOSchema):
    """Output schema for the ChatAgent including the response and suggested questions"""

    internal_thoughts: List[str] = Field(
        ...,
        description="The internal thoughts of the agent as it processes the user's message.",
        default_factory=list,
    )
    answer: str = Field(
        ...,
        description="The main response to the user's query.",
    )
```

Now, it is up to you what to do with this answer.

Let's say you have a look at [the web search example ](https://github.com/BrainBlend-AI/atomic-agents/tree/main/atomic-examples/web-search-agent) you will see we have an agent to generate queries, then we have a search tool that is just traditional code, and then we have an agent interpreting the search results to provide an answer.

Nothing is stopping you from providing a way to the user to modify the queries before they are passed into the search tool, or filtering out search results in some way before sending them to the question-answering agent.

The same would be true if you have a script where an agent talks directly to another agent, it's all just "Input -> Processing -> Output" and it's still your code deciding what to do with the output and whether or not to modify it before sending it off to the next agent

Atomic Agents is all about bringing agentic AI as close to traditional programming as possible and about giving the developer  full control!

**Comment by TheMrguiller** [comment]
Thank you for your quick response  @KennyVaneetvelde. I had some experience with LangGraph and I am searching for alternatives that could potentially facilitate the management of a conversation between a user an a complex RAG system. So basically you support it because us the user are the ones that need to address that kind of problem. It seems an smart way of giving more flexibility.

**Comment by KennyVaneetvelde** [comment]
@TheMrguiller  Yeah, it all stems from the fact that I looked at what was needed in real production use cases and companies, and I figured that nobody is sitting around waiting to relinquish all control to some "team of agents" or even just a single one Devin-style. It never gives you quite what you need, it's a long wait each time you tweak it to see the end result only to discover you need to tweak the initial prompt more, etc etc...

Instead, I identified 2 real main use cases
- RAG Chatbots / Support bots / ... (Duh)
- Well-defined Pipelines (Single-agent, multi-agent, whatever... Think for example: Start -> Email in -> EmailType Analyzer Agent decides whether to call the "Appointment Planner" agent or the "Respond to email" agent -> "Appointment planner is called & uses the appointment tool" -> "Respond to email" agent is called with the original input + extra info that an appointment was planned to formulate an answer -> Exit

All of this of course means every step is easily debuggable/swappable/... and in Atomic Agents, beside the system prompt & context providers, a lot of the prompting comes from the schemas and the docstrings & descriptions contained in them, making sure you have some seriously fine-grained control over your prompting in exactly  the places you expect
