### ISSUE TITLE
How to use groq models?

### ISSUE THREAD

**Issue by ieea** [BrainBlend-AI/atomic-agents#34]
Hi, 
I have installed the atomic agents in the following way, and I was using it through Ollama.

git clone https://github.com/BrainBlend-AI/atomic-agents.git
cd atomic-agents
poetry install

I want to use groq APIs, please guide me or point to the document snippet where I can check the usage of groq apisin atomic agent.

Regards,
Gaurav

**Comment by KennyVaneetvelde** [comment]
Well, judging from the fact the issue is closed, looks like you figured it out!

But for future reference in case anyone stumbles upon this through google etc, an example can be found here: https://github.com/BrainBlend-AI/atomic-agents/blob/main/atomic-examples/quickstart/quickstart/4_basic_chatbot_different_providers.py

And more info can be found here since Atomic Agents just wraps Instructor for its client: https://github.com/instructor-ai/instructor
