### ISSUE TITLE
`BaseAgent` as base class for agents

### ISSUE THREAD

**Issue by anthonytorlucci** [BrainBlend-AI/atomic-agents#36]
Is it possible to use `BaseAgent` as a base class for agents rather than building in `main` from `BaseAgentConfig`? I would like to create the definitions of each agent in separate files and then create an instance of the class in main. Each agent class would need to implement required functions (if any) and overwrite default values specific to the agents purpose.

For example, 

_my_custom_agent.py_
```python
class MyCustomAgent(BaseAgent):
    def __init__(self, <potential additional arguments>):
        super().__init__():
        # overwrite default attributes
        self.system_prompt_generator = SystemPromptGenerator(...)  # custom prompt for this agent
```

_main.py_
```python
# Example usage
if __name__ = "__main__":
    custom_agent = MyCustomAgent()
    input_schema = MyCustomAgentInputSchema(user_message="Having fun with Atomic Agents!")
    custom_agent.run(input_schema)
``` 

Is there a more appropriate pattern when using the atomic agents framework? I see in the deep_research example an instance of `BaseAgent` is created in each agent file, but I'm wondering if it would be better to create the definition in the agent file and create an instance of the class in the main function?

Thank you for taking the time to look over and I appreciate any help or advice moving forward.

**Comment by KennyVaneetvelde** [comment]
Actually, when I first made Atomic Agents, I indeed had foreseen the `BaseAgent` to be extended - as the name might give away.

Pre-v1.0 actually had one extension of the `BaseAgent` integrated into the library, called a `ToolInterfaceAgent` which basically just took a tool as input and would always do the following: `take user input -> generate tool input -> execute tool -> interpret tool output -> formulate answer -> reply to user`

But, in the end while I was working with it, I noticed some times I wanted the flow to be slightly different, and another time different again... In the end it was just easier to always use the `BaseAgent` and implement whatever logic I needed outside of it.

And so, in v1.0 finally, it was removed and only the `BaseAgent` remained.

Now, of course what you want to do is totally different from what I was doing there, but personally, I have settled for the pattern that you can find inside, for example, the `deep-research` example or the `web-search-agent`.

But, if you find a cool use case that I have not thought of, please share it in the discussions tab once you have something worked out I'd absolutely love to see it and we can maybe even add it as an example with your permission (or you can).

Or, if it's just because you enjoy it more than the pattern that is present, I don't see why it would hurt you as long as you are consistent with it in your own codebase (but that goes for all code anywhere, really)

Either way, I am sure there are going to be some real good use cases for extending, I just haven't found any yet, but that's why I kept the name `BaseAgent` so as to signal that there's not reason why you couldn't extend it!

Hope that answers your question!

**Comment by anthonytorlucci** [comment]
That does the answer my question and I appreciate the response. 

I was looking at your [deep_research](https://github.com/BrainBlend-AI/atomic-agents/tree/main/atomic-examples/deep-research) example as a template for the chat bot I'm working on myself (also for research). My apprehension comes with creating an instance of `BaseAgent` in an agent python file, e.g., `question_answering_agent` in [qa_agent](https://github.com/BrainBlend-AI/atomic-agents/blob/main/atomic-examples/deep-research/deep_research/agents/qa_agent.py). 

Feeling more comfortable with c++ and now rust, I typically create the objects in main() unless they are const. The chat bot I'm working on (streamlit app) will (hopefully) have dropdowns for different clients/models (and potentially other arguments, e.g. temperature) to choose at runtime so the agent should really be initialized in `main` (right?).

I'll keep exploring the library and let you know if/when I have to share with the community. Thanks for all the hard work.

**Comment by KennyVaneetvelde** [comment]
Yeah, I admit it looks a bit weird at first if you come from C++ or Rust (My first foray into coding was going out to the book store with my pocket money and buying a C++ book when I was 13 😁 so I do see where you are coming from)

But, this pattern is quite common in Python - it's known as a **module-level instance**.

I like to think of it as a type of global variable.

Generally, I wouldn't use this pattern as it has some downsides usually, but since agents don't really change once created, and since I usually want them to be shared / globally available, I don't think any of the perceived downsides are actual downsides.

But again, Atomic Agents should be flexible enough to handle however you want to do it, no reason you can't initialize agents in `main` like you suggest, if that's what you need (I know streamlit can be fickly when it comes to what is initialized where, due to caching etc)
