### ISSUE TITLE
Example web search agent has an empty   `__init__.py` file

### ISSUE THREAD

**Issue by chrisaww** [BrainBlend-AI/atomic-agents#50]
It may be that poetry ignores this issue but I have move to uv for package management and get an error when installing dependencies.
Apologies if this is trivial, but I make no claim to being an expert in this field

**Comment by KennyVaneetvelde** [comment]
You are correct, Poetry ignores this!

I have removed the init file, along with other unused empty init files from the examples

Thanks for letting me know!

Do be warned, though, I also prefer using uv over Poetry in general, but if you ever plan on contributing to the framework, you might run into issues as uv currently doesn't yet support the monorepo structure in the same way that poetry does, at least it didn't the last time I tried (which is why this repo uses poetry currently) - So, be aware of this if you run into any other issues

Thanks again for letting me know and happy holidays!

**Comment by chrisaww** [comment]
Thanks for your advice. I was suspicious it was a uv issue.I will contribute when I feel I have got my mind in line with your approach.In the meantime, I am very impressed with the example agents that you have provided.The only minor quirk for me are the changes I have to make to use Ollama.  consistently keeping the llm specification in a config.py file for all examples would be helpfulregards
    On Saturday 28 December 2024 at 13:07:54 GMT, Kenny Vaneetvelde ***@***.***> wrote:  
 
 


You are correct, Poetry ignores this!

I have removed the init file, along with other unused empty init files from the examples

Thanks for letting me know!

Do be warned, though, I also prefer using uv over Poetry in general, but if you ever plan on contributing to the framework, you might run into issues as uv currently doesn't yet support the monorepo structure in the same way that poetry does, at least it didn't the last time I tried (which is why this repo uses poetry currently) - So, be aware of this if you run into any other issues

Thanks again for letting me know and happy holidays!
